### ISSUE TITLE
Add tabs to switch sections and problems

### ISSUE THREAD

**Issue by piperswe** [ID10T-Errors/signum-workshop-client#19]
Issues involving this:
- ~~#18~~
- ~~#20~~

Branches working on this:
- [`tabs`](https://github.com/ID10T-Errors/signum-workshop-client/tree/tabs)

**Comment by piperswe** [comment]
Nearly finished, @ztaylor54 do you have an opinion on the tabs?

**Comment by ztaylor54** [comment]
I'll look when I get home.
