### ISSUE TITLE
We cannot add code-editor to this project

### ISSUE THREAD

**Issue by piperswe** [ID10T-Errors/signum-workshop-client#6]
It uses a GPL license while this uses Apache. You cannot include a GPL project in an Apache project.

**Comment by ztaylor54** [comment]
Can you not sublicense it? I'm fairly certain you can.

**Comment by ztaylor54** [comment]
http://www.apache.org/licenses/GPL-compatibility.html

Guess they're incompatible.

**Comment by piperswe** [comment]
Yup. I'm asking on OpenSource.SE to see if there's a way: http://opensource.stackexchange.com/questions/2190/how-would-it-be-possible-to-distribute-a-gpl-program-with-an-apache-program

**Comment by piperswe** [comment]
From what I see, you are able to relicense the code to users of Signum under a different license. Unfortunately, we'd probably need to write our own Apache-compatible license.

**Comment by ztaylor54** [comment]
My father is an attorney. I would probably be able to get help.

**Comment by piperswe** [comment]
Sounds good.

**Comment by piperswe** [comment]
For syntax highlighting there's a library called highlight.js we can use: https://highlightjs.org/

**Comment by piperswe** [comment]
Or we could just use the Ace editor (BSD licensed): https://ace.c9.io/
